spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giveaway
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

debug: false